"""Generate sandbox DDL and audits from contract; --check is offline."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SQL = ROOT / "infra/bigquery/sandbox"

def render(c):
    ns = c["project"] + "." + c["dataset"]
    ddl = [f"CREATE SCHEMA IF NOT EXISTS `{ns}` OPTIONS(location='{c['location']}');"]
    checks, audits = [], []
    for name, table in c["tables"].items():
        fields = table["fields"]
        assert len({f["name"] for f in fields}) == len(fields), name
        full = f"`{ns}.{name}`"
        cols = ",\n".join("  `"+f["name"]+"` "+f["type"]+
                           (" NOT NULL" if f["required"] else "") for f in fields)
        ddl.append(f"CREATE TABLE IF NOT EXISTS {full} (\n{cols}\n)\nCLUSTER BY "+
                   ", ".join(table["cluster"])+";")
        expected = "\nUNION ALL\n".join(
            f"SELECT '{f['name']}' AS column_name, '{f['type']}' AS data_type, "+
            f"'{('NO' if f['required'] else 'YES')}' AS is_nullable" for f in fields)
        checks.append(f"ASSERT (WITH expected AS ({expected}), actual AS ("
            f"SELECT column_name,data_type,is_nullable FROM `{ns}.INFORMATION_SCHEMA.COLUMNS` "
            f"WHERE table_name='{name}' AND is_system_defined='NO') "
            "SELECT COUNT(*)=0 FROM expected e FULL OUTER JOIN actual a USING(column_name) "
            "WHERE e.column_name IS NULL OR a.column_name IS NULL OR e.data_type!=a.data_type "
            f"OR e.is_nullable!=a.is_nullable) AS '{name}: schema mismatch';")
        scoped = f"SELECT * FROM {full} WHERE scenario_id=@scenario_id"
        def add(rule, query):
            audits.append(f"SELECT '{name}' AS table_name,'{rule}' AS rule_id,"
                          f"COUNT(*) AS violations FROM ({query})")
        for rule, keys in [('duplicate_key',table['key']),
                           ('duplicate_idempotency',table.get('idempotency_scope',[]))]:
            if keys:
                group = ", ".join(keys)
                add(rule,f"SELECT {group} FROM ({scoped}) GROUP BY {group} HAVING COUNT(*)>1")
        invalid=[]
        for f in fields:
            n="`"+f["name"]+"`"
            if f["required"]:
                invalid.append(n+" IS NULL")
                if f["type"]=="STRING": invalid.append("TRIM("+n+")=''")
            if "allowed" in f:
                invalid.append(n+" NOT IN ("+",".join("'"+v+"'" for v in f["allowed"])+")")
            if "pattern" in f:
                invalid.append(f"NOT REGEXP_CONTAINS({n},r'{f['pattern']}')")
        add('invalid_fields',f"SELECT 1 FROM ({scoped}) WHERE "+" OR ".join(invalid))
        if name!='scenarios':
            add('scenario_reference',f"SELECT 1 FROM ({scoped}) e WHERE NOT EXISTS ("
                f"SELECT 1 FROM `{ns}.scenarios` s WHERE s.scenario_id=e.scenario_id)")
    header="-- Generated by scripts/verify/sandbox_contract.py; do not edit.\n"
    return {"001_schema.sql":header+"\n\n".join(ddl)+"\n",
            "verify_schema.sql":header+"\n\n".join(checks)+"\n",
            "audit_contract.sql":header+"-- @scenario_id STRING required.\n"+
              "\nUNION ALL\n".join(audits)+"\nORDER BY table_name,rule_id;\n"}

if __name__=="__main__":
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check",action="store_true")
    args=p.parse_args()
    c=json.loads((ROOT/"data/contracts/sandbox/bank_sandbox_v1.json").read_text(encoding="utf-8-sig"))
    SQL.mkdir(parents=True,exist_ok=True)
    for name,content in render(c).items():
        path=SQL/name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8-sig")!=content:
                raise SystemExit(f"Stale generated SQL: {path}")
        else:
            path.write_text(content,encoding="utf-8")
    print("Sandbox contract/SQL consistent. BigQuery validation remains pending.")
