-- Generated by scripts/verify/sandbox_contract.py; do not edit.
CREATE SCHEMA IF NOT EXISTS `hackaton-509923.bank_sandbox` OPTIONS(location='us-central1');

CREATE TABLE IF NOT EXISTS `hackaton-509923.bank_sandbox.scenarios` (
  `scenario_id` STRING NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `created_by` STRING NOT NULL,
  `scenario_clock` TIMESTAMP NOT NULL,
  `products_run_id` STRING NOT NULL,
  `transactions_run_id` STRING NOT NULL
)
CLUSTER BY scenario_id;

CREATE TABLE IF NOT EXISTS `hackaton-509923.bank_sandbox.card_blocks` (
  `block_id` STRING NOT NULL,
  `scenario_id` STRING NOT NULL,
  `customer_id` STRING NOT NULL,
  `idempotency_key` STRING NOT NULL,
  `request_hash` STRING NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `actor_service` STRING NOT NULL,
  `correlation_id` STRING NOT NULL,
  `mode` STRING NOT NULL,
  `contract_version` STRING NOT NULL,
  `card_id` STRING NOT NULL,
  `products_run_id` STRING NOT NULL,
  `status` STRING NOT NULL
)
CLUSTER BY scenario_id, customer_id;

CREATE TABLE IF NOT EXISTS `hackaton-509923.bank_sandbox.disputes` (
  `case_id` STRING NOT NULL,
  `scenario_id` STRING NOT NULL,
  `customer_id` STRING NOT NULL,
  `idempotency_key` STRING NOT NULL,
  `request_hash` STRING NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `actor_service` STRING NOT NULL,
  `correlation_id` STRING NOT NULL,
  `mode` STRING NOT NULL,
  `contract_version` STRING NOT NULL,
  `transaction_id` STRING NOT NULL,
  `transactions_run_id` STRING NOT NULL,
  `status` STRING NOT NULL
)
CLUSTER BY scenario_id, customer_id;

CREATE TABLE IF NOT EXISTS `hackaton-509923.bank_sandbox.handoffs` (
  `ticket_id` STRING NOT NULL,
  `scenario_id` STRING NOT NULL,
  `customer_id` STRING NOT NULL,
  `idempotency_key` STRING NOT NULL,
  `request_hash` STRING NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `actor_service` STRING NOT NULL,
  `correlation_id` STRING NOT NULL,
  `mode` STRING NOT NULL,
  `contract_version` STRING NOT NULL,
  `packet` JSON NOT NULL
)
CLUSTER BY scenario_id, customer_id;

CREATE TABLE IF NOT EXISTS `hackaton-509923.bank_sandbox.notifications` (
  `delivery_id` STRING NOT NULL,
  `scenario_id` STRING NOT NULL,
  `customer_id` STRING NOT NULL,
  `idempotency_key` STRING NOT NULL,
  `request_hash` STRING NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `actor_service` STRING NOT NULL,
  `correlation_id` STRING NOT NULL,
  `mode` STRING NOT NULL,
  `contract_version` STRING NOT NULL,
  `ticket_id` STRING NOT NULL,
  `status` STRING NOT NULL
)
CLUSTER BY scenario_id, customer_id;
