-- Generated by scripts/verify/sandbox_contract.py; do not edit.
ASSERT (WITH expected AS (SELECT 'scenario_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'created_at' AS column_name, 'TIMESTAMP' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'created_by' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'scenario_clock' AS column_name, 'TIMESTAMP' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'products_run_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'transactions_run_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable), actual AS (SELECT column_name,data_type,is_nullable FROM `hackaton-509923.bank_sandbox.INFORMATION_SCHEMA.COLUMNS` WHERE table_name='scenarios' AND is_system_defined='NO') SELECT COUNT(*)=0 FROM expected e FULL OUTER JOIN actual a USING(column_name) WHERE e.column_name IS NULL OR a.column_name IS NULL OR e.data_type!=a.data_type OR e.is_nullable!=a.is_nullable) AS 'scenarios: schema mismatch';

ASSERT (WITH expected AS (SELECT 'block_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'scenario_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'customer_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'idempotency_key' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'request_hash' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'created_at' AS column_name, 'TIMESTAMP' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'actor_service' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'correlation_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'mode' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'contract_version' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'card_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'products_run_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'status' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable), actual AS (SELECT column_name,data_type,is_nullable FROM `hackaton-509923.bank_sandbox.INFORMATION_SCHEMA.COLUMNS` WHERE table_name='card_blocks' AND is_system_defined='NO') SELECT COUNT(*)=0 FROM expected e FULL OUTER JOIN actual a USING(column_name) WHERE e.column_name IS NULL OR a.column_name IS NULL OR e.data_type!=a.data_type OR e.is_nullable!=a.is_nullable) AS 'card_blocks: schema mismatch';

ASSERT (WITH expected AS (SELECT 'case_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'scenario_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'customer_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'idempotency_key' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'request_hash' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'created_at' AS column_name, 'TIMESTAMP' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'actor_service' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'correlation_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'mode' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'contract_version' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'transaction_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'transactions_run_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'status' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable), actual AS (SELECT column_name,data_type,is_nullable FROM `hackaton-509923.bank_sandbox.INFORMATION_SCHEMA.COLUMNS` WHERE table_name='disputes' AND is_system_defined='NO') SELECT COUNT(*)=0 FROM expected e FULL OUTER JOIN actual a USING(column_name) WHERE e.column_name IS NULL OR a.column_name IS NULL OR e.data_type!=a.data_type OR e.is_nullable!=a.is_nullable) AS 'disputes: schema mismatch';

ASSERT (WITH expected AS (SELECT 'ticket_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'scenario_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'customer_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'idempotency_key' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'request_hash' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'created_at' AS column_name, 'TIMESTAMP' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'actor_service' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'correlation_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'mode' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'contract_version' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'packet' AS column_name, 'JSON' AS data_type, 'NO' AS is_nullable), actual AS (SELECT column_name,data_type,is_nullable FROM `hackaton-509923.bank_sandbox.INFORMATION_SCHEMA.COLUMNS` WHERE table_name='handoffs' AND is_system_defined='NO') SELECT COUNT(*)=0 FROM expected e FULL OUTER JOIN actual a USING(column_name) WHERE e.column_name IS NULL OR a.column_name IS NULL OR e.data_type!=a.data_type OR e.is_nullable!=a.is_nullable) AS 'handoffs: schema mismatch';

ASSERT (WITH expected AS (SELECT 'delivery_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'scenario_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'customer_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'idempotency_key' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'request_hash' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'created_at' AS column_name, 'TIMESTAMP' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'actor_service' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'correlation_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'mode' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'contract_version' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'ticket_id' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable
UNION ALL
SELECT 'status' AS column_name, 'STRING' AS data_type, 'NO' AS is_nullable), actual AS (SELECT column_name,data_type,is_nullable FROM `hackaton-509923.bank_sandbox.INFORMATION_SCHEMA.COLUMNS` WHERE table_name='notifications' AND is_system_defined='NO') SELECT COUNT(*)=0 FROM expected e FULL OUTER JOIN actual a USING(column_name) WHERE e.column_name IS NULL OR a.column_name IS NULL OR e.data_type!=a.data_type OR e.is_nullable!=a.is_nullable) AS 'notifications: schema mismatch';
